### ISSUE TITLE
Connection Error, causes process to exit

### ISSUE THREAD

**Issue by wcomartin** [Inrixia/Floatplane-Downloader#104]
As discussed on Discord, 

This connection error causes the process to exit which causes the container to stop, 

```
> Fetching latest videos from [Linus Tech Tips]... Fetched 0 videos! Skipped 0.
Checking for new videos in 5 minutes...
node:internal/process/promises:246
triggerUncaughtException(err, true /* fromPromise */);
^

RequestError: connect ETIMEDOUT 104.16.197.36:443
at ClientRequest.<anonymous> (/fp/node_modules/got/dist/source/core/index.js:956:111)
at Object.onceWrapper (node:events:510:26)
at ClientRequest.emit (node:events:402:35)
at ClientRequest.origin.emit (/fp/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
at TLSSocket.socketErrorListener (node:_http_client:447:9)
at TLSSocket.emit (node:events:390:28)
at emitErrorNT (node:internal/streams/destroy:164:8)
at emitErrorCloseNT (node:internal/streams/destroy:129:3)
at processTicksAndRejections (node:internal/process/task_queues:83:21)
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
code: 'ETIMEDOUT',
timings: {
start: 1637737786289,
socket: 1637737786289,
lookup: 1637737786330,
connect: undefined,
secureConnect: undefined,
upload: undefined,
response: undefined,
end: undefined,
error: 1637737915309,

abort: undefined,
phases: {
wait: 0,
dns: 41,
tcp: undefined,
tls: undefined,
request: undefined,
firstByte: undefined,
download: undefined,
total: 129020
}
}
}
```

**Comment by Inrixia** [comment]
While I will look into this error It's probably a good idea to run your container with auto restart enabled assuming this error is infrequent.

Something I should consider adding to the wiki if its not already there

**Comment by Inrixia** [comment]
Note to self check #106 for a similar error.

Not sure why the request would be timing out. Maybe an issue with the floatplane api, that or a rare bug. Will see

**Comment by Inrixia** [comment]
@guitaristtom @wcomartin Both these errors appear to be due to a timeout occurring with the floatplane api, either due to a issue on their side or the internet on your side dropping out.

Due to the nature of the errors there is no way to nicely recover from them other than to restart which is currently the expected behaviour.

I have added a restart policy to the docker wiki in https://github.com/Inrixia/Floatplane-Downloader/commit/f1f54d0d2362f01bf9c8b7b6c2f0a55582b1cefa

Please let me know if this is still a frequent issue.

**Comment by rpungello** [comment]
I’ve been having similar issues to this, except the container doesn’t automatically restart despite having a restart policy set. Seems like after the error the process doesn’t actually exit, and thus Docker doesn’t detect that a restart is needed. If I restart manually, everything picks back up.

Error I’m getting is:
```
node:internal/process/promises:332
    triggerUncaughtException(err, true /* fromPromise */);
    ^

TypeError: fetch failed
    at node:internal/deps/undici/undici:16416:13
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
    at async Gle (/fp/float.cjs:311:64195)
    at async gq (/fp/float.cjs:311:78717)
    at async /fp/float.cjs:311:85776 {
  [cause]: AggregateError [ETIMEDOUT]: 
      at internalConnectMultiple (node:net:1134:18)
      at internalConnectMultiple (node:net:1210:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1742:5)
      at listOnTimeout (node:internal/timers:607:11)
      at process.processTimers (node:internal/timers:541:7) {
    code: 'ETIMEDOUT',
    [errors]: [
      Error: connect ETIMEDOUT 104.16.124.111:443
          at createConnectionError (node:net:1678:14)
          at Timeout.internalConnectMultipleTimeout (node:net:1737:38)
          at listOnTimeout (node:internal/timers:607:11)
          at process.processTimers (node:internal/timers:541:7) {
        errno: -110,
        code: 'ETIMEDOUT',
        syscall: 'connect',
        address: '104.16.124.111',
        port: 443
      },
      Error: connect ENETUNREACH 2606:4700::6810:7c6f:443 - Local (:::0)
          at internalConnectMultiple (node:net:1206:16)
          at Timeout.internalConnectMultipleTimeout (node:net:1742:5)
          at listOnTimeout (node:internal/timers:607:11)
          at process.processTimers (node:internal/timers:541:7) {
        errno: -101,
        code: 'ENETUNREACH',
        syscall: 'connect',
        address: '2606:4700::6810:7c6f',
        port: 443
      },
      Error: connect ETIMEDOUT 104.16.123.111:443
          at createConnectionError (node:net:1678:14)
          at Timeout.internalConnectMultipleTimeout (node:net:1737:38)
          at listOnTimeout (node:internal/timers:607:11)
          at process.processTimers (node:internal/timers:541:7) {
        errno: -110,
        code: 'ETIMEDOUT',
        syscall: 'connect',
        address: '104.16.123.111',
        port: 443
      },
      Error: connect ENETUNREACH 2606:4700::6810:7b6f:443 - Local (:::0)
          at internalConnectMultiple (node:net:1206:16)
          at Timeout.internalConnectMultipleTimeout (node:net:1742:5)
          at listOnTimeout (node:internal/timers:607:11)
          at process.processTimers (node:internal/timers:541:7) {
        errno: -101,
        code: 'ENETUNREACH',
        syscall: 'connect',
        address: '2606:4700::6810:7b6f',
        port: 443
      }
    ]
  }
}
```

**Comment by Inrixia** [comment]
Yea same note as above. Sadly not much can be done, though the container should either recover or exit on errors like that.

But it's possible you may have gotten unlucky and it didn't.

**Comment by rpungello** [comment]
> though the container should either recover or exit on errors like that

That's the weird part, it never does as far as I can tell. This happens regularly multiple times per week, and it seems like I always have to manually restart the container for things to start working again.

If there's any info I can provide next time it happens I'm happy to do so, but as best I can tell the `entrypoint` command simply isn't terminating properly on this error, which in turn means Docker doesn't restart the container automatically.

I'm not familiar enough with how this image is structured to speculate much further though.

**Comment by Inrixia** [comment]
If I had to guess the error isn't critical enough to actually cause a exit.

There's probably some fixes that can be implemented, but I'm curious if you leave it running does it recover?

If it's not crashing then it should be fine.

**Comment by rpungello** [comment]
As far as I can tell it never recovers. When I check `docker logs` for the instance, it’s not uncommon to see the error was a few days ago and still no restarting.

So you’re probably right, whatever error this is isn’t actually triggering what I presume is a main loop to exit, but it does cause it it stall and stop ingesting new content.
