### ISSUE TITLE
Update to Docker Container Broke

### ISSUE THREAD

**Issue by guitaristtom** [Inrixia/Floatplane-Downloader#157]
Today I pulled the latest push to the `latest` Docker branch, and my container just repeatedly dies and restarts with this error.

```
Node.js v19.8.1
(node:8) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
file:///fp/dist/subscriptionFetching.js:19
            const channelsToAdd = defaultSubChannels[subscription.creator].filter((channel) => sub.channels.findIndex((chan) => chan.title === channel.title) === -1);
                                                                                                            ^

TypeError: sub.channels.findIndex is not a function
    at file:///fp/dist/subscriptionFetching.js:19:109
    at Array.filter (<anonymous>)
    at file:///fp/dist/subscriptionFetching.js:19:76
    at Array.map (<anonymous>)
    at fetchSubscriptions (file:///fp/dist/subscriptionFetching.js:6:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///fp/dist/float.js:81:27

Node.js v19.8.1
> Fetching user subscriptions... > Fetching user subscriptions... > Fetching user subscriptions... > Fetching user subscriptions... > Fetching user subscriptions...
```

It was working correctly before the update. Well.. it was working before the Edge servers were having issues, but I know that was a Floatplane server thing and not this tool.

**Comment by guitaristtom** [comment]
That might be it then. I didn't think about that. I mass-updated all of my containers on my server.

**Comment by Inrixia** [comment]
Yea usually you can just update no issues but the latest update requires a config reset as the format changed to support the new floatplane channels. 

Technically you can edit your existing config to work. But it's faster to regenerate it and then copy over your old settings.
