### ISSUE TITLE
Error: Cannot find ffmpeg

### ISSUE THREAD

**Issue by TomW1605** [Inrixia/Floatplane-Downloader#39]
on windows 7 i am getting this error when evry video finishes downloading
```
TechQuickie> TQ: Better Graphics For F [] 100% 0/0MBError: Cannot find ffmpeg
    at F:\Floatplane-Downloader\node_modules\fluent-ffmpeg\lib\processor.js:136:22 0.20MB/s 69/150MB ETA: 8m 48s
    at FfmpegCommand.proto._getFfmpegPath (F:\Floatplane-Downloader\node_modules\fluent-ffmpeg\lib\capabilities.js:90:14)
    at FfmpegCommand.proto._spawnFfmpeg (F:\Floatplane-Downloader\node_modules\fluent-ffmpeg\lib\processor.js:132:10)
    at FfmpegCommand.proto.availableFormats.proto.getAvailableFormats (F:\Floatplane-Downloader\node_modules\fluent-ffmpeg\lib\capabilities.js:517:10)
    at F:\Floatplane-Downloader\node_modules\fluent-ffmpeg\lib\capabilities.js:568:14
    at nextTask (F:\Floatplane-Downloader\node_modules\async\dist\async.js:5324:14)
    at Object.waterfall (F:\Floatplane-Downloader\node_modules\async\dist\async.js:5334:5)
    at FfmpegCommand.proto._checkCapabilities (F:\Floatplane-Downloader\node_modules\fluent-ffmpeg\lib\capabilities.js:565:11)
    at F:\Floatplane-Downloader\node_modules\fluent-ffmpeg\lib\processor.js:298:14
```

**Comment by Inrixia** [comment]
The ffmpeg library currently used is broken. Anyone who encounters this during install needs to manually download ffmpeg and place it in the folder your script is looking for.

**Comment by Inrixia** [comment]
Fixed with https://github.com/Inrixia/Floatplane-Downloader/commit/10a849bde76d0a3e778a66fe81308c3943d9ffeb
Will be released with v5
