### ISSUE TITLE
Error - throw err

### ISSUE THREAD

**Issue by Powelljl** [Inrixia/Floatplane-Downloader#5]
D:\Install>node float.js
D:\Install\float.js:20
        throw err
        ^

SyntaxError: D:\Install\partial.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:662:27)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Install\float.js:25:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)

D:\Install>pause
Press any key to continue . . .

**Comment by Inrixia** [comment]
This is a error where the partial data file is corrupt/empty. I'm going to be adding a fix for it in the next release but for now just open partial.json in a text editor and make sure it only contains {}

Thay should fix it.
